@startuml

title UC03 - Открытие двери по лицу ([[./uc.puml варианты использования]])

actor Жилец as Tenant
box "Сервис умного дома"
    participant "Домофон" as Intercom
    participant "Умный дом" as SmartHome
end box

box "PropDevelopment"
    participant "tenant-core-app" as TenantCoreApp
end box

Tenant -> Intercom: нажимает кнопку открытия двери домофона (intercom)
Intercom -> Intercom: получает фотоизображение (photo)
Intercom -> SmartHome: сообщение о запросе открытия двери (intercom, photo)
SmartHome -> TenantCoreApp: запрос на проверку [[UC03i1.puml возможности открытия по биометрии]] (photo)
TenantCoreApp -> SmartHome: Открытие разрешено
SmartHome -> Intercom: Команда на открытие
@enduml