@startuml

title UC03 - Открытие двери по лицу ([[./uc.puml варианты использования]])

actor Жилец as Tenant
box "Сервис умного дома"
    participant "Домофон" as Intercom
    participant "Умный дом" as SmartHome
end box

box "PropDevelopment"
    participant "Витрина собственника" as MobileApp
    participant "tenant-core-app" as TenantCoreApp
end box

Tenant -> Intercom: подходит к домофону (intercom)
@enduml